### ISSUE TITLE
Ko

### ISSUE THREAD

**Issue by Goalkov** [MulqiGaming64/TNTExplodeTime#4]
this TNT is infinite, 1 remains and in survival mode it is not wasted, fix it, and also fix the time does not work without setting

**Comment by XanderID** [comment]
can you explain more clearly about the time it doesn't work if it's without settings?

**Comment by XanderID** [comment]
Fixed Please use Latest version
here: https://poggit.pmmp.io/p/TNTExplodeTime/1.0.1
